### ISSUE TITLE
Automatic raw data update using the JHU CCSE dataset

### ISSUE THREAD

**Issue by fletli** [tamas-ferenci/COVID19MagyarEpi#1] opened 2020-03-21 14:03 UTC
I am not an R expert, but If you agree I would add an automatic parsing function to prepare the raw data from:

https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

As far as I  know, the officially reported numbers are updated daily from many countries including Hungary. Using this input the whole analytics could be done for each country, not only for Hungary. It would enable the prompt comparison of the regions/countries and the mitigation strategies.

**Comment by ferenci-tamas** [comment] 2020-03-21 14:33
Thanks for the suggestion @fletli ! You're absolutely right that an automatic parser would be the elegant solution here. I have actually written such parser:

https://github.com/tamas-ferenci/COVID19MagyarEpi/blob/8c43d7f92ef7952aec43b9a0b61a89ecabab5e5a/RawDataProcess.R#L6-L9

The problem is with the data source. I don't perfectly trust Johns Hopkins due to this: https://github.com/CSSEGISandData/COVID-19/issues/650. As you can see from the above code snippet, I therefore switched to ECDC, but their data, at least as Hungary is concerned, is also obviously incorrect (e.g., zero cases for 18 March).

So as a third iteration, what `RawDataProcess` currently does is that I manually typed the data from NNK (displayed at the bottom of https://koronavirus.gov.hu/, among others), which is clearly a joke, I mean that I manually have to type in data every day, because Hungarian public health authorities can't produce computer-readable data, not even a simple daily case count (on the third week of the outbreak!), which I personally find both outrageous and a disgrace for the entire country, but that's the best I can do presently... I have already indicated this problem, and I really hope that it'll be addressed by the authorities in the near future. As soon as it is done, I'll automatically parse their data. Until that time, I keep this issue open.

**Comment by ferenci-tamas** [comment] 2020-09-05 20:40
@fletli It now automatically updates (and indeed uses JHU CCSE); see my remark on the opening page.

**Closed as completed by ferenci-tamas** 2020-09-05 20:40 UTC
